### ISSUE TITLE
symbol lookup error: libORB_SLAM2.so, undefined symbol: _ZN5DBoW24FORB1LE

### ISSUE THREAD

**Issue by HayatoTajiri** [raulmur/ORB_SLAM2#827]
## I can't run orb_slam2. 

|*environment(環境)*|
|-|
|Jetson nano| 
|Ubuntu 18.04LTS|
|ROS melodic|
|opencv ver.3.3.1|

I had used orb_slam2 on jetson nano with Ros melodic.
However I haven't been able to use Orb_slam2 before installing Realsense r200 drivers(librealsense,realsense_camera,etc). Probably.

error content(エラー内容)

Using with Ros
`
$ rosrun ORB_SLAM2 RGBD Vocabulary/ORBvoc.txt Examples/RGB-D/TUM1.yaml
/opt/ros/melodic/share/ORB_SLAM2/RGBD: symbol lookup error: /home/hayato/orb_slam2_ws/ORB_SLAM2/Examples/ROS/ORB_SLAM2/../../../lib/libORB_SLAM2.so: undefined symbol: _ZN5DBoW24FORB1LE
` 
Using without Ros
`
$ ~/orb_slam2_ws/ORB_SLAM2/Examples/Monocular/mono_tum Vocabulary/ORBvoc.txt Examples/Monocular/TUM1.yaml
/home/hayato/orb_slam2_ws/ORB_SLAM2/Examples/Monocular/mono_tum: symbol lookup error: /home/hayato/orb_slam2_ws/ORB_SLAM2/lib/libORB_SLAM2.so: undefined symbol: _ZN5DBoW24FORB1LE
`

I can't understand what causes.
please tell me solutions,anyone.
thanks.

**Comment by mathuse** [comment]
> ## I can't run orb_slam2.
> _environment(環境)_
> Jetson nano
> Ubuntu 18.04LTS
> ROS melodic
> opencv ver.3.3.1
> I had used orb_slam2 on jetson nano with Ros melodic.
> However I haven't been able to use Orb_slam2 before installing Realsense r200 drivers(librealsense,realsense_camera,etc). Probably.
> 
> error content(エラー内容)
> 
> Using with Ros
> `$ rosrun ORB_SLAM2 RGBD Vocabulary/ORBvoc.txt Examples/RGB-D/TUM1.yaml /opt/ros/melodic/share/ORB_SLAM2/RGBD: symbol lookup error: /home/hayato/orb_slam2_ws/ORB_SLAM2/Examples/ROS/ORB_SLAM2/../../../lib/libORB_SLAM2.so: undefined symbol: _ZN5DBoW24FORB1LE`
> Using without Ros
> `$ ~/orb_slam2_ws/ORB_SLAM2/Examples/Monocular/mono_tum Vocabulary/ORBvoc.txt Examples/Monocular/TUM1.yaml /home/hayato/orb_slam2_ws/ORB_SLAM2/Examples/Monocular/mono_tum: symbol lookup error: /home/hayato/orb_slam2_ws/ORB_SLAM2/lib/libORB_SLAM2.so: undefined symbol: _ZN5DBoW24FORB1LE`
> 
> I can't understand what causes.
> please tell me solutions,anyone.
> thanks.

hi,i have the same problem now,and did you have solved it?

**Comment by FaikVural** [comment]
I have same problem, Please help us

**Comment by HayatoTajiri** [comment]
Hi.
Finally, I could't solve it but, I 
formated SDcard and reinstalled ubuntu, so it is running.

**Comment by SkylerGao** [comment]
I also have the same problem, maybe the version problem of DBOW ? Waiting for the solution from "Big God (Chinese words)"...

**Comment by SkylerGao** [comment]
forgot to say... I met the problem in ORB-SLAM3

**Comment by segozcan** [comment]
I encountered the same issue with ORB_SLAM2. What solved the issue for me was moving ORB_SLAM2 to a different directory whch had not been built by catkin build. In my case, I had tried to add new packages to the workspace and build them with catkin_build. Undoing that solved the problem for me.

**Comment by wh200720041** [comment]
Hi this is caused by repetitive installation of DBoW2 in my case. I searched for the DBoW2 in my computer and removed all files named *DBoW2* under /usr/local and the problem was solved

**Comment by Viky397** [comment]
Hi, I've tried that @wh200720041 and the error still persists for me. Any other recommendations? Thanks!

**Comment by wh200720041** [comment]
> Hi, I've tried that @wh200720041 and the error still persists for me. Any other recommendations? Thanks!

Make sure all previous DBoW is removed, including DBoW folder and its related files under /usr/.

**Comment by dnaglucose** [comment]
1、
`ldd -r libORB_SLAM3.so`
find:
`libDBoW2.so => xxxxx/xxxxx/xxxxx/lib/libDBoW2.so`
remove this libDBoW2.so and make again, can solved this problem

==================================
2、/ORB_SLAM2/Thirdparty/DBoW2/CMakeLists.txt  or /ORB_SLAM3/Thirdparty/DBoW2/CMakeLists.txt  
from：
add_library(DBoW2 SHARED ${SRCS_DBOW2} ${SRCS_DUTILS})
target_link_libraries(DBoW2 ${OpenCV_LIBS})
to：
add_library(DBoW2_1 SHARED ${SRCS_DBOW2} ${SRCS_DUTILS})
target_link_libraries(DBoW2_1 ${OpenCV_LIBS})

then：open   /ORB_SLAM2/CMakeLists.txt
from：
${PROJECT_SOURCE_DIR}/Thirdparty/DBoW2/lib/libDBoW2.so
to：
${PROJECT_SOURCE_DIR}/Thirdparty/DBoW2/lib/libDBoW2_1.so


https://blog.csdn.net/qq_35942419/article/details/117163042

**Comment by Shivelino** [comment]
> Hi this is caused by repetitive installation of DBoW2 in my case. I searched for the DBoW2 in my computer and removed all files named _DBoW2_ under /usr/local and the problem was solved

correct, DBoW2 is one of thirdparties, but I have installed one before

**Comment by mathuse** [comment]
Thank you very much.



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 12, 2022 18:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [raulmur/ORB_SLAM2] symbol lookup error: libORB_SLAM2.so,undefined symbol: _ZN5DBoW24FORB1LE (#827)




  
Hi this is caused by repetitive installation of DBoW2 in my case. I searched for the DBoW2 in my computer and removed all files named DBoW2 under /usr/local and the problem was solved
  
correct, DBoW2 is one of thirdparties, but I have installed one before

**Comment by tigerschweiger** [comment]
> Hi this is caused by repetitive installation of DBoW2 in my case. I searched for the DBoW2 in my computer and removed all files named _DBoW2_ under /usr/local and the problem was solved

It works! Thx a lot~
